# @package _global_
benchmark_id: OptBench
problem_id: Ackley-2
problem:
  _target_: optbench.optbench_problem.OptBenchProblem
  function:
    _target_: optbench.functions.Ackley
    dim: 2
    seed: ${seed}
task:
  n_trials: 50
  n_objectives: 1
