# @package _global_
benchmark_id: OptBench
problem_id: Ackley-10
problem:
  _target_: optbench.optbench_problem.OptBenchProblem
  function:
    _target_: optbench.functions.Ackley
    dim: 10
    seed: ${seed}
task:
  n_trials: 250
  n_objectives: 1
