# @package _global_
benchmark_id: OptBench
problem_id: Levy-10
problem:
  _target_: optbench.optbench_problem.OptBenchProblem
  function:
    _target_: <class 'optbench.functions.Levy'>
    dim: 10
    seed: ${seed}
task:
  n_trials: 250
  n_objectives: 1
