# @package _global_
benchmark_id: OptBench
problem_id: synth-Ackley-5
problem:
  _target_: optbench.optbench_problem.OptBenchProblem
  function:
    _target_: optbench.functions.Ackley
    dim: 5
    seed: ${seed}
task:
  n_trials: 125
  n_objectives: 1
  n_initial_design: 15
