PY_EXPERIMENTER:
  n_jobs: 1

  Database:
    provider: mysql
    database: synthacticbench
    table:
      name: jobs
      keyfields:
        benchmarklib:
          type: VARCHAR(255)
          values: ['synthacticbench']
        scenario:
          type: VARCHAR(255)
          values: ['c1', 'c2-ackley', 'c2-rosenbrock', 'c3', 'c4', 'c5', 'c6', 'c7', 'o1', 'o2', 'o3', 'o4-OP','o4-NOP', 'o5', 'o6', 'o7']
        algorithm_configurator:
          type: VARCHAR(255)
          values: ['smac']
        n_trials:
          type: INT
          values: [100,1000]
        seed:
          type: INT
          values: [0,1,2,3,4]
      result_timestamps: False
      resultfields:
        incumbent: TEXT
        f_min: VARCHAR(255)
        regret: VARCHAR(255)
        incumbent_cost: VARCHAR(255)
        incumbent_found_at: VARCHAR(255)
        done: VARCHAR(50)
