PY_EXPERIMENTER:
  n_jobs: 1

  Database:
    provider: mysql
    database: synthacticbench
    table:
      name: jobs_smac
      keyfields:
        benchmarklib:
          type: VARCHAR(255)
          values: ['synthacticbench']
        scenario:
          type: VARCHAR(255)
          values: ['s1', 's2-ackley', 's2-rosenbrock', 's3', 's4', 's5', 's6', 's7', 'o1', 'o2', 'o3', 'o4-OP', 'o5', 'o6', 'o7']
        algorithm_configurator:
          type: VARCHAR(255)
          values: ['smac']#, 'random', 'irace']
        n_trials:
          type: INT
          values: [100]
        num_instances:
          type: INT
          values: [700]
        seed:
          type: INT
          values: [0]
      result_timestamps: False
      resultfields:
        incumbent: TEXT
        f_min: VARCHAR(255)
        regret: VARCHAR(255)
        incumbent_cost: VARCHAR(255)
        incumbent_found_at: VARCHAR(255)
        done: VARCHAR(50)
    logtables:
      incumbent_log:
        n_trials: VARCHAR(255)
        incumbent: TEXT
        incumbent_cost: VARCHAR(255)
      trial_log:
        n_trials: VARCHAR(255)
        trial_config: TEXT
        instance: VARCHAR(255)
        trial_cost: VARCHAR(255)
        n_function_calls: VARCHAR(255)
