# @package _global_
optimizer_id: SMAC3-ACFacade
optimizer_container_id: SMAC3
optimizer:
  _target_: carps.optimizers.smac20.SMAC3Optimizer
  _partial_: true

  smac_cfg:
    smac_class: smac.facade.AlgorithmConfigurationFacade
    scenario:
      seed: ${seed}
      n_trials: ${task.n_trials}
      deterministic: true
      n_workers: 1
      instances: null
      output_directory: ${outdir}/${seed}/smac3_output
    smac_kwargs:
      dask_client: null
      overwrite: true
      multi_objective_algorithm:
        _target_: smac.multi_objective.parego.ParEGO
        _partial_: true
