# @package _global_
benchmark_id: SynthACticBench
problem_id: ParameterInteractions-rosenbrock
problem:
  _target_: synthacticbench.synthacticbench_problem.SynthACticBenchProblem
  function:
    _target_: synthacticbench.configuration_space_functions.MixedTypes
    dim: 20
    share_cat: 0.25
    share_bool: 0.25
    share_int: 0.25
    share_float: 0.25
    seed: 52
task:
  n_trials: 100
  time_budget: null
  n_workers: 1
  n_objectives: 1
  objectives:
    - quality
  is_multifidelity: false
  fidelity_type: null
  min_budget: null
  max_budget: null
  has_constraints: false
  domain: synthetic
  objective_function_approximation: real
  has_virtual_time: false
  deterministic: true
  dimensions: 10
  search_space_n_categoricals: 10
  search_space_n_ordinals: 0
  search_space_n_integers: 5
  search_space_n_floats: 5
  search_space_has_conditionals: false
  search_space_has_forbiddens: false
  search_space_has_priors: false
