# @package _global_
instance_parameter: 0.0

benchmark_id: SynthACticBench
problem_id: DeterministicObjective
problem:
  _target_: synthacticbench.synthacticbench_problem.SynthACticBenchProblem
  function:
    _target_: synthacticbench.objective_functions.DeterministicObjective
    wrapped_bench:
      _target_: synthacticbench.objective_functions.NoisyEvaluation
      instance_parameter: ${instance_parameter}
      dim: 10
      seed: 52
      distribution: no_noise
task:
  n_trials: 100
  time_budget: null
  n_workers: 1
  n_objectives: 1
  objectives:
    - quality
  is_multifidelity: false
  fidelity_type: null
  min_budget: null
  max_budget: null
  has_constraints: false
  domain: synthetic
  objective_function_approximation: real
  has_virtual_time: false
  deterministic: false
  dimensions: 10
  search_space_n_categoricals: 0
  search_space_n_ordinals: 0
  search_space_n_integers: 0
  search_space_n_floats: 10
  search_space_has_conditionals: false
  search_space_has_forbiddens: false
  search_space_has_priors: false
