# @package _global_
benchmark_id: SynthACticBench
problem_id: InvalidParametrisation-1
problem:
  _target_: synthacticbench.synthacticbench_problem.SynthACticBenchProblem
  function:
    _target_: synthacticbench.functions.ParameterInteractions
    dim: 10
    name: rosenbrock
    seed: 52
